# Generated by Django 2.2.5 on 2022-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('profile_image', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('is_like', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['feed_id'], name='photo_zone__feed_id_5efbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['feed_id'], name='photo_zone__feed_id_907389_idx'),
        ),
    ]
